# Site settings
title: Technical Blog
subtitle: "Suman Pal"
email: mail.suman.sss@gmail.com
description: "My technical blog"
baseurl: ""
url: "http://palsuman.github.io/"
twitter_username: "fumansun"
github_username:  "palsuman"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed